//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniHealthWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> UserPhone { get; set; }
        public string Mail { get; set; }
        public string UserMessage { get; set; }
    }
}
